[package]
name = "dynamic_aes_encryptor"
version = "0.1.0"
authors = ["Nxs67 <nxs67@jabber.calyxinstitute.org>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.9.0"
rand = "0.8.5"
walkdir = "2.3.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
